name: KSA Animal & Plant Alerts

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run Monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Commit Database
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add sent_alerts.json

          git diff --cached --quiet || git commit -m "Update sent alerts"

          git push
